import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // wasm-bindgen-generated bindings (regenerated by `wasm-bindgen`, see
    // ../HANDOVER.md's M4 section) — not hand-written, not ours to lint.
    // lib/wasm/index.ts is the hand-written wrapper and stays linted.
    "lib/wasm/crochet_wasm.js",
    "lib/wasm/crochet_wasm.d.ts",
    "lib/wasm/crochet_wasm_bg.wasm.d.ts",
  ]),
]);

export default eslintConfig;
